### ISSUE TITLE
[UI Fix]: SignUp Page

### ISSUE THREAD

**Issue by EffDuBois** [akashgreninja/Doggonation#56]
|   ✨  |   request                |
|-----|---------------------------------|
| **Is your feature request related to a problem?** | Signup page style is not consistent with the rest of the website |
| **Describe the solution you'd like** | <li>Redo the UI style of the Signin Page to Match the Rest of the project |
| **Additional context** | This is done to make the style of the website more consistent |

**Comment by rishuraj1** [comment]
I would really like to work on this one. I might be able to revamp the signup page completely. @EffDuBois 

- I plan to change the background color of the page to a solid color like cyan or linear gradient
- I would contain the signup form and the background image in one single flexbox side by side 
- Further I plan to change the form (i.e., buttons, icons etc.) to make it more visually attractive
- Overall I want to make it more user friendly so that user does not have to scroll a bit for the button to signup, containing the whole content in screen size.

proposed rough idea : 

![image](https://github.com/akashgreninja/Doggonation/assets/47839626/d9fd4e45-98f0-4975-be19-83f768ca4cec)


I would like to contribute to this wonderful project under GSSoC '23 thank you!

**Comment by rishuraj1** [comment]
@EffDuBois alright! Thanks for the insight, although I am not sure if I got it, Our objective here is: 
 - to fix the style of the form 
 - change the bg of the page
 Can you briefly explain the not changing layout and matching the theme with post component ? Thank You !

**Comment by EffDuBois** [comment]
@rishuraj1 the main objective is to - **fix the style of the form and the div**.
- try to keep with the posts as it's in the direction of the look we want from the website.

As a side objective, If you think something will be more appropriate for the bg you have the freedom replace it. But you don't need to.

I don't want to change the layout because of 3 reasons 1. To keep the UI super minimal
                                                                                         2.  To keep it in sync with the signup page
                                                                                         3.  A design reason- The current Ui focuses more on the login and less on the Background, because as a social media website our focus is the user and their experience , that's why most popular social media websites have a minimal login page. Your idea would work well if we were an art website or something. Like adobe, it's uI and login has a similar layout to what you suggested, it's their way of saying that art is forefront.

**Comment by rishuraj1** [comment]
@EffDuBois thank you for the feedback.  I understood the assignment, now, could you please assign me to this task under GSSoC.   I am excited to work on this. Thank You!

**Comment by EffDuBois** [comment]
@rishuraj1 the layout is changed, and the colour combo used does not go together. As I instructed earlier, please use the old layout and modify the font, and the box. And accomodate the whole signup page in the screen

**Comment by rishuraj1** [comment]
@EffDuBois  alright! thanks for the feedback.
