### ISSUE TITLE
Make the sigin page more responsive

### ISSUE THREAD

**Issue by akashgreninja** [akashgreninja/Doggonation#7]
Most of the buttons have been cut in half and the options button does not work on top of the page fix it asap please

**Comment by EffDuBois** [comment]
It's a structural issue rather than a issue with z-index or related. Changing the z-index of the button has no effect since the z index of the whole navbar is messed up. and increasing the z-index of the navbar results in the whole content part of the page not working.
I have opened a new issue about the structure of the page.

**Comment by syedawanya18** [comment]
I want to work on this issue as a contributor.
Pleasure Assign so that I can show my skills under GSSoC'23.

**Comment by EffDuBois** [comment]
issue fixed on signin page
